// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HillarysHairCare.Migrations
{
    [DbContext(typeof(HillarysHairDbContext))]
    [Migration("20260611192947_RebuildSeedData")]
    partial class RebuildSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HillarysHairCare.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppointmentTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<int>("StylistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StylistId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentTime = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            IsCancelled = false,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentTime = new DateTime(2026, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            IsCancelled = false,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentTime = new DateTime(2026, 6, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            IsCancelled = false,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 4,
                            AppointmentTime = new DateTime(2026, 6, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            IsCancelled = false,
                            StylistId = 4
                        },
                        new
                        {
                            Id = 5,
                            AppointmentTime = new DateTime(2026, 6, 18, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 6,
                            IsCancelled = false,
                            StylistId = 5
                        },
                        new
                        {
                            Id = 6,
                            AppointmentTime = new DateTime(2026, 6, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 9,
                            IsCancelled = false,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 7,
                            AppointmentTime = new DateTime(2026, 5, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            IsCancelled = true,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 8,
                            AppointmentTime = new DateTime(2026, 6, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            IsCancelled = true,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 9,
                            AppointmentTime = new DateTime(2026, 5, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 8,
                            IsCancelled = false,
                            StylistId = 6
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 10,
                            IsCancelled = false,
                            StylistId = 3
                        });
                });

            modelBuilder.Entity("HillarysHairCare.Models.AppointmentService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AppointmentServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 1,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 2,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 3,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 4,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 5,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 7,
                            AppointmentId = 6,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 8,
                            AppointmentId = 7,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 9,
                            AppointmentId = 8,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 10,
                            AppointmentId = 9,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 11,
                            AppointmentId = 9,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 12,
                            AppointmentId = 10,
                            ServiceId = 1
                        });
                });

            modelBuilder.Entity("HillarysHairCare.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "homer@springfield.net",
                            Name = "Homer Simpson",
                            Phone = "555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bart@springfield.net",
                            Name = "Bart Simpson",
                            Phone = "555-0102"
                        },
                        new
                        {
                            Id = 3,
                            Email = "lisa@springfield.net",
                            Name = "Lisa Simpson",
                            Phone = "555-0103"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ned@leftorium.com",
                            Name = "Ned Flanders",
                            Phone = "555-0104"
                        },
                        new
                        {
                            Id = 5,
                            Email = "mburns@burnscorp.com",
                            Name = "Montgomery Burns",
                            Phone = "555-0105"
                        },
                        new
                        {
                            Id = 6,
                            Email = "apu@kwikmart.com",
                            Name = "Apu Nahasapeemapetilon",
                            Phone = "555-0106"
                        },
                        new
                        {
                            Id = 7,
                            Email = "cwiggum@spd.gov",
                            Name = "Chief Clancy Wiggum",
                            Phone = "555-0107"
                        },
                        new
                        {
                            Id = 8,
                            Email = "krusty@krustyco.com",
                            Name = "Krusty the Clown",
                            Phone = "555-0108"
                        },
                        new
                        {
                            Id = 9,
                            Email = "ralph@spd.gov",
                            Name = "Ralph Wiggum",
                            Phone = "555-0109"
                        },
                        new
                        {
                            Id = 10,
                            Email = "",
                            Name = "Hans Moleman",
                            Phone = "555-0110"
                        });
                });

            modelBuilder.Entity("HillarysHairCare.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Basic cut and trim",
                            Name = "Haircut",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Full single-color treatment",
                            Name = "Color Treatment",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Permanent wave styling",
                            Name = "Perm",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Partial or full highlights",
                            Name = "Highlights",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Wash and blowout style",
                            Name = "Blowout",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Shampoo, condition, and style",
                            Name = "Shampoo & Style",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Beard shaping and trim",
                            Name = "Beard Trim",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Haircut for ages 12 and under",
                            Name = "Kids Cut",
                            Price = 18.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Color, highlights, cut, and style package",
                            Name = "Full Makeover",
                            Price = 200.00m
                        });
                });

            modelBuilder.Entity("HillarysHairCare.Models.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Stylists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Marge Simpson",
                            isActive = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Selma Bouvier",
                            isActive = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Patty Bouvier",
                            isActive = true
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lindsey Naegle",
                            isActive = true
                        },
                        new
                        {
                            Id = 5,
                            Name = "Helen Lovejoy",
                            isActive = true
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sideshow Bob",
                            isActive = false
                        },
                        new
                        {
                            Id = 7,
                            Name = "Snake Jailbird",
                            isActive = false
                        });
                });

            modelBuilder.Entity("HillarysHairCare.Models.Appointment", b =>
                {
                    b.HasOne("HillarysHairCare.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HillarysHairCare.Models.Stylist", "Stylist")
                        .WithMany("Appointments")
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Stylist");
                });

            modelBuilder.Entity("HillarysHairCare.Models.AppointmentService", b =>
                {
                    b.HasOne("HillarysHairCare.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HillarysHairCare.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HillarysHairCare.Models.Customer", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HillarysHairCare.Models.Stylist", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
